"""Hardcoded set lists for the grading calculator set/card pickers.

Set IDs are the catalog APIs' own ids (pokemontcg.io for Pokemon, optcgapi
for One Piece) and are passed straight to set_import.fetch_*_set_cards. Baked
from a live fetch on 2026-07-24 so the ids are real, not guessed. New sets
release a few times a year - append them here (or type the card in by hand).

Ordered newest-first, matching how the catalog returns them.
"""

GRADING_SETS = {
    "pokemon": [
        {"id": "me5", "name": "Pitch Black", "year": "2026"},
        {"id": "me4", "name": "Chaos Rising", "year": "2026"},
        {"id": "me3", "name": "Perfect Order", "year": "2026"},
        {"id": "me2pt5", "name": "Ascended Heroes", "year": "2026"},
        {"id": "me2", "name": "Phantasmal Flames", "year": "2025"},
        {"id": "me1", "name": "Mega Evolution", "year": "2025"},
        {"id": "zsv10pt5", "name": "Black Bolt", "year": "2025"},
        {"id": "rsv10pt5", "name": "White Flare", "year": "2025"},
        {"id": "sv10", "name": "Destined Rivals", "year": "2025"},
        {"id": "sv9", "name": "Journey Together", "year": "2025"},
        {"id": "sv8pt5", "name": "Prismatic Evolutions", "year": "2025"},
        {"id": "sv8", "name": "Surging Sparks", "year": "2024"},
        {"id": "sv7", "name": "Stellar Crown", "year": "2024"},
        {"id": "sv6pt5", "name": "Shrouded Fable", "year": "2024"},
        {"id": "sv6", "name": "Twilight Masquerade", "year": "2024"},
        {"id": "sv5", "name": "Temporal Forces", "year": "2024"},
        {"id": "sv4pt5", "name": "Paldean Fates", "year": "2024"},
        {"id": "sv4", "name": "Paradox Rift", "year": "2023"},
        {"id": "sv3pt5", "name": "151", "year": "2023"},
        {"id": "sv3", "name": "Obsidian Flames", "year": "2023"},
        {"id": "sv2", "name": "Paldea Evolved", "year": "2023"},
        {"id": "sve", "name": "Scarlet & Violet Energies", "year": "2023"},
        {"id": "sv1", "name": "Scarlet & Violet", "year": "2023"},
        {"id": "swsh12pt5gg", "name": "Crown Zenith Galarian Gallery", "year": "2023"},
        {"id": "swsh12pt5", "name": "Crown Zenith", "year": "2023"},
        {"id": "svp", "name": "Scarlet & Violet Black Star Promos", "year": "2023"},
        {"id": "swsh12tg", "name": "Silver Tempest Trainer Gallery", "year": "2022"},
        {"id": "swsh12", "name": "Silver Tempest", "year": "2022"},
        {"id": "swsh11tg", "name": "Lost Origin Trainer Gallery", "year": "2022"},
        {"id": "swsh11", "name": "Lost Origin", "year": "2022"},
        {"id": "mcd22", "name": "McDonald's Collection 2022", "year": "2022"},
        {"id": "pgo", "name": "Pokémon GO", "year": "2022"},
        {"id": "swsh10tg", "name": "Astral Radiance Trainer Gallery", "year": "2022"},
        {"id": "swsh10", "name": "Astral Radiance", "year": "2022"},
        {"id": "swsh9tg", "name": "Brilliant Stars Trainer Gallery", "year": "2022"},
        {"id": "swsh9", "name": "Brilliant Stars", "year": "2022"},
        {"id": "swsh8", "name": "Fusion Strike", "year": "2021"},
        {"id": "cel25c", "name": "Celebrations: Classic Collection", "year": "2021"},
        {"id": "cel25", "name": "Celebrations", "year": "2021"},
        {"id": "swsh7", "name": "Evolving Skies", "year": "2021"},
        {"id": "swsh6", "name": "Chilling Reign", "year": "2021"},
        {"id": "swsh5", "name": "Battle Styles", "year": "2021"},
        {"id": "swsh45", "name": "Shining Fates", "year": "2021"},
        {"id": "swsh45sv", "name": "Shining Fates Shiny Vault", "year": "2021"},
        {"id": "mcd21", "name": "McDonald's Collection 2021", "year": "2021"},
        {"id": "swsh4", "name": "Vivid Voltage", "year": "2020"},
        {"id": "swsh35", "name": "Champion's Path", "year": "2020"},
        {"id": "fut20", "name": "Pokémon Futsal Collection", "year": "2020"},
        {"id": "swsh3", "name": "Darkness Ablaze", "year": "2020"},
        {"id": "swsh2", "name": "Rebel Clash", "year": "2020"},
        {"id": "swsh1", "name": "Sword & Shield", "year": "2020"},
        {"id": "swshp", "name": "SWSH Black Star Promos", "year": "2019"},
        {"id": "sm12", "name": "Cosmic Eclipse", "year": "2019"},
        {"id": "mcd19", "name": "McDonald's Collection 2019", "year": "2019"},
        {"id": "sma", "name": "Hidden Fates Shiny Vault", "year": "2019"},
        {"id": "sm115", "name": "Hidden Fates", "year": "2019"},
        {"id": "sm11", "name": "Unified Minds", "year": "2019"},
        {"id": "sm10", "name": "Unbroken Bonds", "year": "2019"},
        {"id": "det1", "name": "Detective Pikachu", "year": "2019"},
        {"id": "sm9", "name": "Team Up", "year": "2019"},
        {"id": "sm8", "name": "Lost Thunder", "year": "2018"},
        {"id": "mcd18", "name": "McDonald's Collection 2018", "year": "2018"},
        {"id": "sm75", "name": "Dragon Majesty", "year": "2018"},
        {"id": "sm7", "name": "Celestial Storm", "year": "2018"},
        {"id": "sm6", "name": "Forbidden Light", "year": "2018"},
        {"id": "sm5", "name": "Ultra Prism", "year": "2018"},
        {"id": "mcd17", "name": "McDonald's Collection 2017", "year": "2017"},
        {"id": "sm4", "name": "Crimson Invasion", "year": "2017"},
        {"id": "sm35", "name": "Shining Legends", "year": "2017"},
        {"id": "sm3", "name": "Burning Shadows", "year": "2017"},
        {"id": "sm2", "name": "Guardians Rising", "year": "2017"},
        {"id": "smp", "name": "SM Black Star Promos", "year": "2017"},
        {"id": "sm1", "name": "Sun & Moon", "year": "2017"},
        {"id": "xy12", "name": "Evolutions", "year": "2016"},
        {"id": "mcd16", "name": "McDonald's Collection 2016", "year": "2016"},
        {"id": "xy11", "name": "Steam Siege", "year": "2016"},
        {"id": "xy10", "name": "Fates Collide", "year": "2016"},
        {"id": "g1", "name": "Generations", "year": "2016"},
        {"id": "xy9", "name": "BREAKpoint", "year": "2016"},
        {"id": "mcd15", "name": "McDonald's Collection 2015", "year": "2015"},
        {"id": "xy8", "name": "BREAKthrough", "year": "2015"},
        {"id": "xy7", "name": "Ancient Origins", "year": "2015"},
        {"id": "xy6", "name": "Roaring Skies", "year": "2015"},
        {"id": "dc1", "name": "Double Crisis", "year": "2015"},
        {"id": "xy5", "name": "Primal Clash", "year": "2015"},
        {"id": "xy4", "name": "Phantom Forces", "year": "2014"},
        {"id": "xy3", "name": "Furious Fists", "year": "2014"},
        {"id": "mcd14", "name": "McDonald's Collection 2014", "year": "2014"},
        {"id": "xy2", "name": "Flashfire", "year": "2014"},
        {"id": "xy1", "name": "XY", "year": "2014"},
        {"id": "xy0", "name": "Kalos Starter Set", "year": "2013"},
        {"id": "bw11", "name": "Legendary Treasures", "year": "2013"},
        {"id": "xyp", "name": "XY Black Star Promos", "year": "2013"},
        {"id": "bw10", "name": "Plasma Blast", "year": "2013"},
        {"id": "bw9", "name": "Plasma Freeze", "year": "2013"},
        {"id": "bw8", "name": "Plasma Storm", "year": "2013"},
        {"id": "bw7", "name": "Boundaries Crossed", "year": "2012"},
        {"id": "dv1", "name": "Dragon Vault", "year": "2012"},
        {"id": "bw6", "name": "Dragons Exalted", "year": "2012"},
        {"id": "mcd12", "name": "McDonald's Collection 2012", "year": "2012"},
        {"id": "bw5", "name": "Dark Explorers", "year": "2012"},
        {"id": "bw4", "name": "Next Destinies", "year": "2012"},
        {"id": "bw3", "name": "Noble Victories", "year": "2011"},
        {"id": "bw2", "name": "Emerging Powers", "year": "2011"},
        {"id": "mcd11", "name": "McDonald's Collection 2011", "year": "2011"},
        {"id": "bw1", "name": "Black & White", "year": "2011"},
        {"id": "bwp", "name": "BW Black Star Promos", "year": "2011"},
        {"id": "col1", "name": "Call of Legends", "year": "2011"},
        {"id": "hgss4", "name": "HS—Triumphant", "year": "2010"},
        {"id": "hgss3", "name": "HS—Undaunted", "year": "2010"},
        {"id": "hgss2", "name": "HS—Unleashed", "year": "2010"},
        {"id": "hsp", "name": "HGSS Black Star Promos", "year": "2010"},
        {"id": "hgss1", "name": "HeartGold & SoulSilver", "year": "2010"},
        {"id": "ru1", "name": "Pokémon Rumble", "year": "2009"},
        {"id": "pl4", "name": "Arceus", "year": "2009"},
        {"id": "pl3", "name": "Supreme Victors", "year": "2009"},
        {"id": "pl2", "name": "Rising Rivals", "year": "2009"},
        {"id": "pop9", "name": "POP Series 9", "year": "2009"},
        {"id": "pl1", "name": "Platinum", "year": "2009"},
        {"id": "dp7", "name": "Stormfront", "year": "2008"},
        {"id": "pop8", "name": "POP Series 8", "year": "2008"},
        {"id": "dp6", "name": "Legends Awakened", "year": "2008"},
        {"id": "dp5", "name": "Majestic Dawn", "year": "2008"},
        {"id": "pop7", "name": "POP Series 7", "year": "2008"},
        {"id": "dp4", "name": "Great Encounters", "year": "2008"},
        {"id": "dp3", "name": "Secret Wonders", "year": "2007"},
        {"id": "pop6", "name": "POP Series 6", "year": "2007"},
        {"id": "dp2", "name": "Mysterious Treasures", "year": "2007"},
        {"id": "dpp", "name": "DP Black Star Promos", "year": "2007"},
        {"id": "dp1", "name": "Diamond & Pearl", "year": "2007"},
        {"id": "pop5", "name": "POP Series 5", "year": "2007"},
        {"id": "ex16", "name": "Power Keepers", "year": "2007"},
        {"id": "ex15", "name": "Dragon Frontiers", "year": "2006"},
        {"id": "ex14", "name": "Crystal Guardians", "year": "2006"},
        {"id": "pop4", "name": "POP Series 4", "year": "2006"},
        {"id": "ex13", "name": "Holon Phantoms", "year": "2006"},
        {"id": "pop3", "name": "POP Series 3", "year": "2006"},
        {"id": "tk2b", "name": "EX Trainer Kit 2 Minun", "year": "2006"},
        {"id": "tk2a", "name": "EX Trainer Kit 2 Plusle", "year": "2006"},
        {"id": "ex12", "name": "Legend Maker", "year": "2006"},
        {"id": "ex11", "name": "Delta Species", "year": "2005"},
        {"id": "pop2", "name": "POP Series 2", "year": "2005"},
        {"id": "ex10", "name": "Unseen Forces", "year": "2005"},
        {"id": "ex9", "name": "Emerald", "year": "2005"},
        {"id": "ex8", "name": "Deoxys", "year": "2005"},
        {"id": "ex7", "name": "Team Rocket Returns", "year": "2004"},
        {"id": "pop1", "name": "POP Series 1", "year": "2004"},
        {"id": "ex6", "name": "FireRed & LeafGreen", "year": "2004"},
        {"id": "tk1a", "name": "EX Trainer Kit Latias", "year": "2004"},
        {"id": "tk1b", "name": "EX Trainer Kit Latios", "year": "2004"},
        {"id": "ex5", "name": "Hidden Legends", "year": "2004"},
        {"id": "ex4", "name": "Team Magma vs Team Aqua", "year": "2004"},
        {"id": "ex3", "name": "Dragon", "year": "2003"},
        {"id": "np", "name": "Nintendo Black Star Promos", "year": "2003"},
        {"id": "ex2", "name": "Sandstorm", "year": "2003"},
        {"id": "ex1", "name": "Ruby & Sapphire", "year": "2003"},
        {"id": "ecard3", "name": "Skyridge", "year": "2003"},
        {"id": "ecard2", "name": "Aquapolis", "year": "2003"},
        {"id": "bp", "name": "Best of Game", "year": "2002"},
        {"id": "ecard1", "name": "Expedition Base Set", "year": "2002"},
        {"id": "base6", "name": "Legendary Collection", "year": "2002"},
        {"id": "neo4", "name": "Neo Destiny", "year": "2002"},
        {"id": "neo3", "name": "Neo Revelation", "year": "2001"},
        {"id": "si1", "name": "Southern Islands", "year": "2001"},
        {"id": "neo2", "name": "Neo Discovery", "year": "2001"},
        {"id": "neo1", "name": "Neo Genesis", "year": "2000"},
        {"id": "gym2", "name": "Gym Challenge", "year": "2000"},
        {"id": "gym1", "name": "Gym Heroes", "year": "2000"},
        {"id": "base5", "name": "Team Rocket", "year": "2000"},
        {"id": "base4", "name": "Base Set 2", "year": "2000"},
        {"id": "base3", "name": "Fossil", "year": "1999"},
        {"id": "basep", "name": "Wizards Black Star Promos", "year": "1999"},
        {"id": "base2", "name": "Jungle", "year": "1999"},
        {"id": "base1", "name": "Base", "year": "1999"},
    ],
    "one_piece": [
        {"id": "OP-16", "name": "The Time of Battle", "year": ""},
        {"id": "OP15-EB04", "name": "Adventure on Kami's Island", "year": ""},
        {"id": "EB-03", "name": "Extra Booster: One Piece Heroines Edition", "year": ""},
        {"id": "OP14-EB04", "name": "The Azure Sea's Seven", "year": ""},
        {"id": "OP-13", "name": "Carrying On His Will", "year": ""},
        {"id": "PRB-02", "name": "Premium Booster - The Best - Vol. 2", "year": ""},
        {"id": "PRB-01", "name": "Premium Booster - The Best", "year": ""},
        {"id": "OP-12", "name": "Legacy of the Master", "year": ""},
        {"id": "EB-02", "name": "Extra Booster: Anime 25th Collection", "year": ""},
        {"id": "OP-11", "name": "A Fist of Divine Speed", "year": ""},
        {"id": "OP-10", "name": "Royal Blood", "year": ""},
        {"id": "OP-09", "name": "Emperors in the New World", "year": ""},
        {"id": "OP-08", "name": "Two Legends", "year": ""},
        {"id": "EB-01", "name": "Extra Booster: Memorial Collection", "year": ""},
        {"id": "OP-07", "name": "500 Years in the Future", "year": ""},
        {"id": "OP-06", "name": "Wings of the Captain", "year": ""},
        {"id": "OP-05", "name": "Awakening of the New Era", "year": ""},
        {"id": "OP-04", "name": "Kingdoms of Intrigue", "year": ""},
        {"id": "OP-03", "name": "Pillars of Strength", "year": ""},
        {"id": "OP-02", "name": "Paramount War", "year": ""},
        {"id": "OP-01", "name": "Romance Dawn", "year": ""},
    ],
}
